### ISSUE TITLE
 const struct CreatureInfo’ has no member named ‘CreatureTypeFlags'

### ISSUE THREAD

**Issue by DarkElfRaider** [scriptdev2/scriptdev2-cata#21]
Hi,

I am getting the following error when trying to compile

server/src/bindings/scriptdev2-cata/base/follower_ai.cpp                                                                                                                                                             : In member function ‘bool FollowerAI::AssistPlayerInCombat(Unit*)’:
server/src/bindings/scriptdev2-cata/base/follower_ai.cpp                                                                                                                                                             :52:42: error: ‘const struct CreatureInfo’ has no member named ‘CreatureTypeFlags’
make[2]: *** [src/bindings/scriptdev2-cata/CMakeFiles/mangosscript.dir/base/follower_ai.cpp.o] Error 1
make[1]: *** [src/bindings/scriptdev2-cata/CMakeFiles/mangosscript.dir/all] Error 2
make: *** [all] Error 2

Have pulled down the latest repo (about 2 hours ago).

Trying to compile on Debian 7.8 x64

Cheers
DarkElfRaider

**Comment by xfurry** [comment]
Which core are you using? 
If you have https://github.com/cmangos/mangos-cata then it shouldn't be any problem

**Comment by DarkElfRaider** [comment]
Hi,

I am using https://github.com/mangosthree, will give cmangos a go.

Cheers
DarkElfRadier
